version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    image: ouxs19/project2cs:file-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./files:/usr/share/nginx/html