apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: ouxs19/cdn:frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: ENDPOINT_IP
              value: backend-service.default.svc.cluster.local
            - name: ENDPOINT_PORT
              value: "4000"
