apiVersion: v1
kind: Pod
metadata:
  name: front-pod
spec:
  containers:
    - name: front
      image: ouxs19/cdn:frontend
      ports:
        - containerPort: 3000
      env:
        - name: ENDPOINT_IP
          value: backend
        - name: ENDPOINT_PORT
          value: "4000"
