apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70