apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002