version: '3.8'

services:

  backend:
    build:
      context: cdn_backend-master
      dockerfile: Dockerfile
    ports:  
      - '4000:4000'
    image: 172.16.0.1:1000/backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ENDPOINT_IP=172.16.0.1
      - ENDPOINT_PORT=80
      - HAPROXY_PORT=193.194.77.246
      - HAPROXY_PORT=80
    volumes:
      - ./file-backend-server/files:/cdn

  file:
    build:
      context: file-backend-server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    image: 172.16.0.1:1000/file-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./file-backend-server/files:/usr/share/nginx/html

  front:
    build:
      context: frontend-prjs
      dockerfile: Dockerfile
    ports:  
      - '3000:3000'
    image: 172.16.0.1:1000/frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ENDPOINT_IP=backend
      - ENDPOINT_PORT=4000
