version: '3.8'

services:

  backend:
    build:
      context: cdn_backend-master
      dockerfile: Dockerfile
    ports:  
      - '4000:4000'
    image: ouxs19/project2cs:backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ENDPOINT_IP=file
      - ENDPOINT_PORT=80
    volumes:
      - ./file-backend-server/files:/cdn

  file:
    build:
      context: file-backend-server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    image: ouxs19/project2cs:file-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./file-backend-server/files:/usr/share/nginx/html

  front:
    build:
      context: frontend-prjs
      dockerfile: Dockerfile
    ports:  
      - '3000:3000'
    image: ouxs19/project2cs:frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ENDPOINT_IP=backend
      - ENDPOINT_PORT=4000