apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: 172.16.0.1:1000/file-server
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
          volumeMounts:
            - name: file-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: file-volume
          hostPath:
            path: /cdn
