apiVersion: v1
kind: Pod
metadata:
  name: file-pod
spec:
  containers:
    - name: file
      image: ouxs19/cdn:file-server
      ports:
        - containerPort: 80
      volumeMounts:
        - name: file-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: file-volume
      hostPath:
        path: /cdn
