apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: ouxs19/cdn:file-server
          ports:
            - containerPort: 80
          volumeMounts:
            - name: file-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: file-volume
          hostPath:
            path: /cdn
