apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    app: file
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000