version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      - '3000:3000'
    image: ouxs19/project2cs:frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ENDPOINT_IP=10.0.10.157
      - ENDPOINT_PORT=4000