apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ouxs19/cdn:backend
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          env:
            - name: ENDPOINT_IP
              value: file-service.default.svc.cluster.local
            - name: ENDPOINT_PORT
              value: "80"
          volumeMounts:
            - name: backend-volume
              mountPath: /cdn
      volumes:
        - name: backend-volume
          hostPath:
            path: /cdn
