apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
    - name: backend
      image: ouxs19/cdn:backend
      ports:
        - containerPort: 4000
      env:
        - name: ENDPOINT_IP
          value: file
        - name: ENDPOINT_PORT
          value: "80"
      volumeMounts:
        - name: backend-volume
          mountPath: /cdn
  volumes:
    - name: backend-volume
      hostPath:
        path: /path/to/file-backend-server/files
