apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32002
